$(window).load(function(){FusionCharts.ready(function () {
    var salesMap = new FusionCharts({
        type: 'usa',
        renderAt: 'chart-container',
        width: '600',
        height: '400',
        dataFormat: 'json',
        dataSource: {
            "chart": {
                "caption": "Sales by State",
                "subcaption": "Last week",                
                "numberPrefix": "$",                
                "theme": "fint",
                "showLabels": "1",
                "entityFillHoverColor": "#cccccc"
            },
            "colorrange": {
                "minvalue": "90000",
                "startlabel": "Low",
                "endlabel": "High",
                "code": "#e44a00",
                "gradient": "1",
                "color": [
                    {
                        "maxvalue": "1500000",
                        "displayvalue": "Average",
                        "code": "#f8bd19"
                    },
                    {
                        "maxvalue": "2950000",
                        "code": "#6baa01"
                    }
                ]
            },
            "data": [{
                "id": "HI",
                "showLabel": "0",
                "value": ""
            }, {
                "id": "DC",
                "value": "879000"
            }, {
                "id": "MD",
                "value": "90000"
            }, {
                "id": "DE",
                "value": "467000"
            }, {
                "id": "RI",
                "value": "490000"
            }, {
                "id": "WA",
                "value": "927000"
            }, {
                "id": "OR",                
                "value": "1798000"
            }, {
                "id": "CA",                
                "value": "1861000"
            }, {
                "id": "AK",
                "showLabel": "0",
                "value": ""
            }, {
                "id": "ID",                
                "value": "2662000"
            }, {
                "id": "NV",
                "value": "1041000"
            }, {
                "id": "AZ",                
                "value": "1558000"
            }, {
                "id": "MT",               
                "value": "2942000"
            }, {
                "id": "WY",                
                "value": "2834000"
            }, {
                "id": "UT",                
                "value": "1512000"
            }, {
                "id": "CO",
                "value": "2026000"
            }, {
                "id": "NM",
                "value": "1365000"
            }, {
                "id": "ND",                
                "value": "1554000"
            }, {
                "id": "SD",                
                "value": "1722000"
            }, {
                "id": "NE",                
                "value": "1736000"
            }, {
                "id": "KS",
                "value": "1681000"
            }, {
                "id": "OK",
                "value": "2038000"
            }, {
                "id": "TX",
                "value": "1425000"
            }, {
                "id": "MN",                
                "value": "1485000"
            }, {
                "id": "IA",                
                "value": "1515000"
            }, {
                "id": "MO",                
                "value": "1715000"
            }, {
                "id": "AR",                
                "value": "1497000"
            }, {
                "id": "LA",
                "value": "1706000"
            }, {
                "id": "WI",                
                "value": "1382000"
            }, {
                "id": "IL",
                "value": "1202000"
            }, {
                "id": "KY",
                "value": "1118000"
            }, {
                "id": "TN",                
                "value": "1657000"
            }, {
                "id": "MS",                
                "value": "1205000"
            }, {
                "id": "AL",
                "value": "873000"
            }, {
                "id": "GA",
                "value": "1895000"
            }, {
                "id": "MI",                
                "value": "695000"
            }, {
                "id": "IN",                
                "value": "592000"
            }, {
                "id": "OH",                
                "value": "1960000"
            }, {
                "id": "PA",                
                "value": "346000"
            }, {
                "id": "NY",                
                "value": "828000"
            }, {
                "id": "VT",
                "value": "1411000"
            }, {
                "id": "NH",                
                "value": "1403000"
            }, {
                "id": "ME",                
                "value": "1636000"
            }, {
                "id": "MA",                
                "value": "1767000"
            }, {
                "id": "CT",                
                "value": "1353000"
            }, {
                "id": "NJ",
                "value": "788000"
            }, {
                "id": "WV",
                "value": "890000"
            }, {
                "id": "VA",
                "value": "1140000"
            }, {
                "id": "NC",
                "value": "1344000"
            }, {
                "id": "SC",
                "value": "1234000"
            }, {
                "id": "FL",
                "value": "882000"
            }]
        }
    }).render();
});});